
#spring:
#  datasource:
#      url: jdbc:mysql://118.31.122.126:3306/test2?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=GMT%2B8
#      username: Jesse
#      password: Jesse@123456
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      hikari:
#        connection-timeout: 20000
#        minimum-idle: 10
#        maximum-pool-size: 50
#        pool-name: hikari_jdbc_conn_pool
#        auto-commit: true
spring:
  rabbitmq:
    listener:
      simple:
        retry:
          # 允许消息消费失败的重试
          enabled: true
          # 允许消息消费失败的重试3次
          max-attempts: 3
          # 消息多次消费的间隔1秒
          initial-interval: 1000
          #  设置为false，会丢弃消息或者重新发布到死信队列
        default-requeue-rejected: false
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
    host: 118.31.122.126
    port: 5672
    username: Jesse
    password:  Jesse@123456
    virtual-host: /
    connection-timeout: 5000

gateway:
  server:
    name: nio-gataway
    version: 2.0.0
    port: 8888
    context-path: /api/
    keep-alive: true
